FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .
RUN npm run build
# этап production (production-stage)
FROM nginx:stable-alpine as production-stage
RUN mkdir -p /usr/share/nginx/html/front
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/proxy_params /etc/nginx/proxy_params
EXPOSE 8081
CMD ["nginx", "-g", "daemon off;"]
